# Generated by Django 5.2 on 2025-06-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingresult',
            name='heatmap_intensity',
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='processed_slices',
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='result_file_path',
        ),
        migrations.AddField(
            model_name='processingresult',
            name='ece_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='heatmap_file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='non_ece_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='nrrd_file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='slice_counts_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='dicom_series',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_result', to='dicom_processor.dicomseries'),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='result_type',
            field=models.CharField(default='heatmap_and_prediction', max_length=50),
        ),
    ]
