# Generated by Django 5.2 on 2025-08-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_processor', '0002_remove_processingresult_heatmap_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='heatmap_vti_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
