# Generated by Django 5.2.8 on 2026-02-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_processor', '0003_processingresult_heatmap_vti_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseries',
            name='series_instance_uid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
