# Generated by Django 5.2.11 on 2026-05-06 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_processor', '0004_dicomseries_series_instance_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_image_quality', models.IntegerField(blank=True, null=True)),
                ('q2_consistency', models.IntegerField(blank=True, null=True)),
                ('q3_noise', models.IntegerField(blank=True, null=True)),
                ('q4_canal_clear', models.CharField(blank=True, max_length=50, null=True)),
                ('q5_confidence_q4', models.IntegerField(blank=True, null=True)),
                ('q6_emergency_pathology', models.CharField(blank=True, max_length=50, null=True)),
                ('q7_confidence_q6', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicom_processor.dicomseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
