upstream slicerwebapp {
    server web:8000;
}

server {
    listen 80;
    server_name siollab.duckdns.org;
    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all other HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name siollab.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/siollab.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/siollab.duckdns.org/privkey.pem;

    # Recommended SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 100M;

    location / {
        proxy_pass http://slicerwebapp;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    # Protected media handled by Django X-Accel-Redirect
    location /protected_media/ {
        internal;
        alias /app/media/;
    }
}
